version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_NAME}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - seed
    ports:
      - "3000:3000"
    image: "next-app"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_CONTAINER_NAME}:${DB_PORT}/${DB_NAME}
    networks:
      - app-network

  seed:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.seed
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: "seed"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_CONTAINER_NAME}:${DB_PORT}/${DB_NAME}
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
